.PHONY: all build test proto clean

all: build

# Build the server and CLI binaries
build:
	go build -o bin/server ./cmd/server
	go build -o bin/jobctl ./cmd/jobctl

# Run tests with the race detector
test:
	go test -race ./...

# Generate protobuf
proto:
	protoc --go_out=. --go_opt=paths=source_relative \
	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	       proto/jobworker.proto

clean:
	rm -rf bin
